"""Define foreign key relationship

Revision ID: 2fd47d351ce3
Revises: 8692210f2026
Create Date: 2025-11-12 12:35:23.125639+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '2fd47d351ce3'
down_revision: Union[str, Sequence[str], None] = '8692210f2026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.NVARCHAR(length=36), nullable=False),
    sa.Column('method', sa.NVARCHAR(length=10), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('query_parms', sa.Text(), nullable=True),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('server_name', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('api_version', sa.NVARCHAR(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('start_time', mssql.DATETIME2(), server_default=sa.text('sysdatetime()'), nullable=False),
    sa.Column('end_time', mssql.DATETIME2(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('is_error', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_request_logs_composite', 'request', ['method', 'is_error'], unique=False)
    op.create_index('idx_request_logs_start_time', 'request', ['start_time'], unique=False)
    op.create_index(op.f('ix_request_is_error'), 'request', ['is_error'], unique=False)
    op.create_index(op.f('ix_request_method'), 'request', ['method'], unique=False)
    op.create_index(op.f('ix_request_request_id'), 'request', ['request_id'], unique=True)
    op.create_table('action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.NVARCHAR(length=36), nullable=True),
    sa.Column('action_name', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('module_name', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('function_name', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('input_params', sa.Text(), nullable=True),
    sa.Column('output_results', sa.Text(), nullable=True),
    sa.Column('start_time', mssql.DATETIME2(), server_default=sa.text('sysdatetime()'), nullable=False),
    sa.Column('end_time', mssql.DATETIME2(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('is_error', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('llm_model', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('llm_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_total_tokens', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_logs_composite', 'action', ['request_id', 'action_type', 'is_error'], unique=False)
    op.create_index('idx_action_logs_start_time', 'action', ['start_time'], unique=False)
    op.create_index(op.f('ix_action_action_type'), 'action', ['action_type'], unique=False)
    op.create_index(op.f('ix_action_is_error'), 'action', ['is_error'], unique=False)
    op.create_index(op.f('ix_action_request_id'), 'action', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_request_id'), table_name='action')
    op.drop_index(op.f('ix_action_is_error'), table_name='action')
    op.drop_index(op.f('ix_action_action_type'), table_name='action')
    op.drop_index('idx_action_logs_start_time', table_name='action')
    op.drop_index('idx_action_logs_composite', table_name='action')
    op.drop_table('action')
    op.drop_index(op.f('ix_request_request_id'), table_name='request')
    op.drop_index(op.f('ix_request_method'), table_name='request')
    op.drop_index(op.f('ix_request_is_error'), table_name='request')
    op.drop_index('idx_request_logs_start_time', table_name='request')
    op.drop_index('idx_request_logs_composite', table_name='request')
    op.drop_table('request')
    # ### end Alembic commands ###
