"""new long polling tables

Revision ID: 5b5aa96c1dc7
Revises: 5b99949a7078
Create Date: 2025-12-10 10:40:18.555000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5aa96c1dc7'
down_revision: Union[str, Sequence[str], None] = '5b99949a7078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_action_request_id'), table_name='action')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_action_request_id'), 'action', ['request_id'], unique=False)
    op.alter_column('action', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
