"""new long polling tables

Revision ID: 80d81ef9f9eb
Revises: bdaefc9c3543
Create Date: 2025-12-10 09:56:50.966072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d81ef9f9eb'
down_revision: Union[str, Sequence[str], None] = 'bdaefc9c3543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
