"""Job table

Revision ID: 816c9fa619c7
Revises: d34204c751e5
Create Date: 2025-12-10 00:52:58.943800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '816c9fa619c7'
down_revision: Union[str, Sequence[str], None] = 'd34204c751e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.NVARCHAR(length=36), nullable=False),
    sa.Column('status', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('start_time', mssql.DATETIME2(), server_default=sa.text('sysdatetime()'), nullable=False),
    sa.Column('end_time', mssql.DATETIME2(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_status', 'job', ['status'], unique=False)
    op.create_index(op.f('ix_job_job_id'), 'job', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_status'), 'job', ['status'], unique=False)
    op.add_column('action', sa.Column('job_id', sa.NVARCHAR(length=36), nullable=True))
    op.alter_column('action', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_action_logs_composite', table_name='action')
    op.create_index('idx_action_logs_composite', 'action', ['request_id', 'job_id', 'action_type', 'is_error'], unique=False)
    op.create_index(op.f('ix_action_job_id'), 'action', ['job_id'], unique=False)
    op.add_column('request', sa.Column('job_id', sa.NVARCHAR(length=36), nullable=True))
    op.create_index('idx_request_logs_jobid', 'request', ['job_id'], unique=False)
    op.create_index(op.f('ix_request_job_id'), 'request', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_job_id'), table_name='request')
    op.drop_index('idx_request_logs_jobid', table_name='request')
    op.drop_column('request', 'job_id')
    op.drop_index(op.f('ix_action_job_id'), table_name='action')
    op.drop_index('idx_action_logs_composite', table_name='action')
    op.create_index('idx_action_logs_composite', 'action', ['request_id', 'action_type', 'is_error'], unique=False)
    op.alter_column('action', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('action', 'job_id')
    op.drop_index(op.f('ix_job_status'), table_name='job')
    op.drop_index(op.f('ix_job_job_id'), table_name='job')
    op.drop_index('idx_job_status', table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
