"""Define foreign key relationship

Revision ID: 8692210f2026
Revises: d60318f4215d
Create Date: 2025-11-12 12:33:30.450908+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '8692210f2026'
down_revision: Union[str, Sequence[str], None] = 'd60318f4215d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_request_logs_composite'), table_name='request')
    op.drop_index(op.f('idx_request_logs_start_time'), table_name='request')
    op.drop_index(op.f('ix_request_is_error'), table_name='request')
    op.drop_index(op.f('ix_request_method'), table_name='request')
    op.drop_table('request')
    op.drop_index(op.f('idx_action_logs_composite'), table_name='action')
    op.drop_index(op.f('idx_action_logs_start_time'), table_name='action')
    op.drop_index(op.f('ix_action_action_type'), table_name='action')
    op.drop_index(op.f('ix_action_is_error'), table_name='action')
    op.drop_table('action')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('request_log_id', sa.NVARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.NVARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('action_name', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('module_name', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('function_name', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('line_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('input_params', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('output_results', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('start_time', mssql.DATETIME2(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('end_time', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('error_traceback', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('is_error', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('llm_provider', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('llm_model', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('llm_prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('llm_completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('llm_total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__action__3213E83F3C164D84'))
    )
    op.create_index(op.f('ix_action_is_error'), 'action', ['is_error'], unique=False)
    op.create_index(op.f('ix_action_action_type'), 'action', ['action_type'], unique=False)
    op.create_index(op.f('idx_action_logs_start_time'), 'action', ['start_time'], unique=False)
    op.create_index(op.f('idx_action_logs_composite'), 'action', ['request_log_id', 'action_type', 'is_error'], unique=False)
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.NVARCHAR(length=36, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('method', sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('query_parms', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('headers', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('start_time', mssql.DATETIME2(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('server_name', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('api_version', sa.NVARCHAR(length=10, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_body', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('end_time', mssql.DATETIME2(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('error_traceback', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('is_error', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__request__3213E83FDD837CCE'))
    )
    op.create_index(op.f('ix_request_method'), 'request', ['method'], unique=False)
    op.create_index(op.f('ix_request_is_error'), 'request', ['is_error'], unique=False)
    op.create_index(op.f('idx_request_logs_start_time'), 'request', ['start_time'], unique=False)
    op.create_index(op.f('idx_request_logs_composite'), 'request', ['method', 'is_error'], unique=False)
    # ### end Alembic commands ###
