"""Define foreign key relationship

Revision ID: f4e2379f7051
Revises: 2fd47d351ce3
Create Date: 2025-11-12 12:52:53.813956+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e2379f7051'
down_revision: Union[str, Sequence[str], None] = '2fd47d351ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('query_params', sa.Text(), nullable=True))
    op.drop_column('request', 'query_parms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('query_parms', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('request', 'query_params')
    # ### end Alembic commands ###
